### ISSUE TITLE
multiple Option no working

### ISSUE THREAD

**Issue by FANUP** [FineUploader/react-fine-uploader#124]
my Option is:
```
const uploader = new FineUploaderTraditional({
    options: {
        request: {
           endpoint: ""
        },
        chunking: {
            enabled: true,
            partSize: 524288,
            concurrent: {
                enabled: true
             },
             success: {
                 endpoint: ""
            }
        },
        multiple: false,
        resume: {
           enabled: true
        },
        cors: {
            expected: true
        },
        maxConnections: 1,
        callbacks: {}
    }
})
```

in React:
`<Gallery uploader={ uploader } />`

But,It can still select multiple file to upload

**Comment by rnicholus** [comment]
Please fix your formatting

**Comment by FANUP** [comment]
@rnicholus ok,I already fix my formatting.

**Comment by rnicholus** [comment]
The `multiple` option does not apply to React Fine Uploader, since this is a Fine Uploader UI option. Use the `multiple` prop on the [`<FileInput />`](https://github.com/FineUploader/react-fine-uploader#fileinput-) and [`<Dropzone />`](https://github.com/FineUploader/react-fine-uploader#dropzone-) elements instead.
