### ISSUE TITLE
<uploading with multiple fields>

### ISSUE THREAD

**Issue by anuragcin74** [FineUploader/react-fine-uploader#133]
Is it possible to upload documents  along with multiple fields when click on submit button ?

**Comment by rnicholus** [comment]
Yes, this is possible

**Comment by anuragcin74** [comment]
Hello RNicholous,
Appreciate if you provide me some sample code (React JS) to upload documents along with multiple fields when click on submit button.

**Comment by rnicholus** [comment]
Provide some code showing me where these fields and documents are coming from, and a specific area where you are struggling to complete your project, and I'll be happy to provide advice and adjustments to your code. Otherwise, your question can be mostly answered by looking at Fine Uploader API documentation at https://docs.fineuploader.com/, which React Fine Uploader supports.
