### ISSUE TITLE
Gallery's UI elements do not work when assigning a new uploader

### ISSUE THREAD

**Issue by Lycheepeel** [FineUploader/react-fine-uploader#193]
I have a use case where I need to have a user type the name of a path he wants to store his folders in S3. 

![image](https://user-images.githubusercontent.com/6478682/39961279-c71df256-5600-11e8-9364-864f8535c6ee.png)

If I have the uploader belong to a state variable ```<Gallery uploader={this.state.uploader}/>``` and have the uploader, update to the change in what the user types. The UI will break and not show progress bar or items that were uploaded. However the uploads to S3 are still successful.

The only way that I can get it to work is to force react to de-render the entire Gallery, and then re-render it. (By de-render I have to remove the whole reference to it, so that there is no Virtual DOM drop in replacement)

Is there something I'm missing in the docs regarding support for a dynamic S3 path?

Ideally a ``setObjectProperties``` within the S3 API will suffice for this solution similar to the other set APIs present: https://docs.fineuploader.com/branch/master/api/methods-s3.html#setAcl

_Example Code that does not work._
```
function getNewFineUploader(s3Path) {
  return new FineUploaderS3({
    options: {
       objectProperties: { 
         key: function(id) { return `${s3Path}/${this.getName(id)}`}
       }
    }
    ...
  })
}

export default class ReactFineUploaderWrapperExample extends React.Component {
  constructor() {
  }
  componentDidUpdate(prevProps, prevState, snapshot) {
    if (prevProps === this.props) {
    }
    this.setState({
      uploader: getNewFineUploader(this.props.s3Path)
    });
  }
  render() {
    return (<Gallery uploader={this.state.uploader}/>)
  }
}
```

_Code that does work_
```
export default class ReactFineUploaderWrapperExample extends React.Component {
  constructor() {
  }
  componentDidUpdate(prevProps, prevState, snapshot) {
    if (prevProps === this.props) {
    }
    this.setState({
       renderGallery: false,
    }, () => {
      this.setState({
        renderGallery: true,
        uploader: getNewFineUploader(this.props.s3Path)
      });
    }) 
  }
  render() {
    return ( {this.state.renderGallery ? <Gallery uploader={this.state.uploader}/> : ""})
  }
}
```

**Comment by rnicholus** [comment]
Why are you storing the uploader in a state variable? You’re not actually changing the uploader instance, so that is unnecessary and probably the cause of your issue. You don’t need to create an entirely new uploader instance simply to react to a change in the value that influences the key function. There are a number of better ways to do this, such as passing in a function that returns the current/correct S3 path, or tying the s3 path to some other in-scope variable that reflects user input.

Solution: don’t store the uploader in a state variable and just tie the key function to some other in-scope var
